### ISSUE TITLE
[마이페이지]프로필 변경/구독 OTT/내 리뷰 평점

### ISSUE THREAD

**Issue by wonhyuna** [TAVE-balak/OTTify-frontend#2]
## 🔥 Issue
마이페이지에서 프로필 관련 설정 부분 페이지 구현 (+OTT 선택 페이지 UI)

## ✅ TODO
- [x]  프로필 설정 레이아웃
- [x]  프로필 이미지
- [x]  개인 정보 (이름 (+뱃지), 이메일)
- [x]  프로필 변경 버튼
- [x]  구독 중인 OTT
- [x]  구독 중인 OTT 페이지 레이아웃
- [x]  구독 중인 OTT 타이틀 지정
- [x]  구독 중인 OTT 선택 UI
- [x]  구독 중인 OTT 취소 & 적용 UI
- [x]  OTT 선택 페이지 이동 버튼
- [x] 내 리뷰 평균 평점 표현
- [x] 내 리뷰 평균 평점 그래프
