### ISSUE TITLE
[마이페이지] 콘텐츠 설정 (취향 장르 선택/보고싶어요/관심없어요)

### ISSUE THREAD

**Issue by wonhyuna** [TAVE-balak/OTTify-frontend#4]
## 🔥 Issue
마이페이지에서 내 취향 장르 선택(1순위, 2순위), 보고싶어요, 관심없어요 기능 구현 

## ✅ TODO
- [x]  콘텐츠 레이아웃
- [x]  내 취향 장르 UI (1순위 - 1개)
- [x]  내 취향 장르 UI (2순위 - 여러 개)
- [x]  보고싶어요 UI
- [x]  관심없어요 UI
- [x]  내 취향 장르 2순위 선택 시, 색깔 변경
