### ISSUE TITLE
[마이 페이지, 토론 작성 페이지] 일부 수정

### ISSUE THREAD

**Issue by wonhyuna** [TAVE-balak/OTTify-frontend#43]
## 🔥 Issue
마이 페이지, 토론 작성 페이지 수정 (슬라이드, 프로필 변경 버튼 색, 토론 쓰기 변경 버튼 색)

## ✅ TODO
- [x]  마이페이지 하트, 엑스 지우기
- [x]  프로필 변경 input 기본값
- [x]  토론 쓰기 내용 작성 안 해도 버튼 색깔 변경
- [x]  back 이미지 코드 변경
