### ISSUE TITLE
[메인페이지] 인기 차트 (포스터, 순위, OTT종류, 제목, 연도, 장르, 별점)

### ISSUE THREAD

**Issue by hwi-woong** [TAVE-balak/OTTify-frontend#5]
## 🔥 Issue
메인페이지에서 인기 차트에 해당 하는 부분 기능 구현 (포스터, 순위, OTT종류, 제목, 연도, 장르, 별점 등)

## ✅ TODO
- [ ]  인기차트 상단 글씨
- [ ]  포스터 이미지 배치 
- [ ] 화살표 및 넘어갈 수 있게 기능 구현
- [ ]  순위 이미지 좌측 상단 배치
- [ ]  해당 OTT 정보 이미지 우측 상단 배치
- [ ]  영화 제목
- [ ]  영화 상영 연도 
- [ ]  영화 장르 
- [ ]  영화 별점
- [ ] 이미지 클릭 시, 상세 정보 페이지로 이동
