### ISSUE TITLE
상세페이지

### ISSUE THREAD

**Issue by jyjyjy25** [TAVE-balak/OTTify-frontend#79]
## 🔥 Issue
상세 페이지 API를 연결하고 css를 수정한다.

## ✅ TODO
- [x] 리뷰 API 연결
- [x] OTT API 연결
- [x] 상세 페이지 css 수정
